project:
  type: website
  resources:
    - "img/**"

website:
  title: "RDeWald.com"
  navbar:
    left:
      - href: blog.qmd
        text: Blog
      - href: https://bsky.app/profile/rdewald.substack.com
        text: BlueSky
      - href: https://github.com/rdewald
        text: GitHub
      - href: https://rdewald.substack.com/
        text: Substack

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    page-layout: custom