project:
  type: website
  resources:
    - "img/**"

lang: en

website:
  title: "RDeWald.com"
  site-url: https://rdewald.com
  open-graph: true
  search:
    location: sidebar
    type: overlay
  navbar:
    background: "#7BA4D4"
    foreground: white
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "About"
        href: about.qmd
  sidebar:
    style: docked
    collapse-level: 1
    background: light
    title: "RDeWald.com"
    tools:
      - icon: github
        href: https://github.com/rdewald
        text: "GitHub profile"
      - icon: rss
        href: https://rdewald.substack.com/
        text: "Substack"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - section: "Professional Articles"
        contents:
          - text: "Clinical Informatics"
            href: posts/clinformatics.qmd
          - text: "FAQ"
            href: posts/FAQ.qmd
          - text: "Fees"
            href: posts/fees.qmd
      - text: "About"
        href: about.qmd
  page-footer:
    left: |
      <br>
      Richard DeWald, PhD, RN<br>
      Clinical Informatics & Healthcare Technology<br>
    center: |
      <br>
      Contact: rdewald@rdewald.com<br>
    right: |
      <br>
      Copyright Â© 2025 Richard DeWald<br>
      This website was created with
      [![](/img/banner.png){fig-alt="Quarto" width=65px}](https://quarto.org)<br>

format:
  html:
    date-format: "MMM YYYY"
    theme:
      light:
        - flatly
    css: styles.css
    toc: false
    page-layout: article

execute:
  freeze: auto