project:
  type: website

website:
  title: "rdewald.com"
  navbar:
    left:
      - href: RDRN.qmd
        text: RDRN
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
